# Aider — Qwen3 Coder 30B-A3B profile (RunPod RTX 4090)
# Usage: aider --config .aider-qwen3-coder.conf.yml [files...]

model: ollama_chat/qwen3-coder:30b-a3b-q4_K_M
openai-api-base: https://mrfsueorjb21wo-64411e80-11434.proxy.runpod.net
extra-params: keep_alive=1h

# Commits
auto-commits: false
dirty-commits: false
attribute-author: true
attribute-committer: false

# Output
pretty: true
stream: true
show-diffs: true

# Behaviour
suggest-shell-commands: false
watch-files: false

# Read-only context (always loaded, never edited)
read:
  - AGENTS.md
  - backend/AGENTS.md
  - frontend/AGENTS.md
  - shared/openapi.yaml
