# Aider — GLM-4.7-Flash profile (RunPod RTX 4090)
# Usage: aider --config .aider-glm.conf.yml [files...]

model: openai/glm-4.7-flash:q4_K_M
openai-api-base: https://mrfsueorjb21wo-64411e80-11434.proxy.runpod.net/v1
openai-api-key: ollama
extra-params: keep_alive=1h

# Commits
auto-commits: false
dirty-commits: false
attribute-author: true
attribute-committer: false

# Output
pretty: true
stream: true
show-diffs: true

# Behaviour
suggest-shell-commands: false
watch-files: false

# Read-only context (always loaded, never edited)
read:
  - AGENTS.md
  - backend/AGENTS.md
  - frontend/AGENTS.md
  - shared/openapi.yaml
