image: node:16-buster

stages:
  - quality
  - security
  - publish

cache:
  key:
    files:
      - yarn.lock
    prefix: yarn
  paths:
    - .yarn/cache

sonar-scanner:
  stage: quality
  tags:
    - linux
    - docker
  before_script:
    - curl -o /tmp/vault.zip ${VAULT_BINARY_URL}
    - unzip /tmp/vault.zip -d /usr/local/bin
    - chmod +x /usr/local/bin/vault
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=${VAULT_ROLE} jwt=$CI_JOB_JWT)"
    - export SONAR_LOGIN="$(vault kv get -field=token secrets/open-Digital-Factory/sonarqube/scanner)"
    - yarn config set npmRegistryServer ${NPM_DEFAULT_MIRROR}
  script:
    - yarn install --immutable
    - yarn workspace @aspect/react-ui run test:ci
    - yarn workspace @aspect/design-system run test:ci
    - yarn run prettier --check packages/react-ui/src packages/design-system
    - yarn run sonar-scanner --serverUrl=${SONAR_HOST_URL}

dtrack:
  stage: security
  tags:
    - linux
    - docker
  before_script:
    - curl -o /tmp/vault.zip ${VAULT_BINARY_URL}
    - unzip /tmp/vault.zip -d /usr/local/bin
    - chmod +x /usr/local/bin/vault
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=${VAULT_ROLE} jwt=$CI_JOB_JWT)"
    - export DTRACK_APIKEY="$(vault kv get -field=apikey secrets/open-Digital-Factory/dtrack)"
    - yarn config set npmRegistryServer ${NPM_DEFAULT_MIRROR}
  script:
    - yarn install --immutable
    - yarn workspace @aspect/react-ui run predtrack
    - yarn workspace @aspect/react-ui run dtrack --baseUrl=${DTRACK_BASE_URL}
    - yarn workspace @aspect/design-system run predtrack
    - yarn workspace @aspect/design-system run dtrack --baseUrl=${DTRACK_BASE_URL}
  allow_failure: true

npm-publish:
  stage: publish
  tags:
    - linux
    - docker
  before_script:
    - curl -o /tmp/vault.zip ${VAULT_BINARY_URL}
    - unzip /tmp/vault.zip -d /usr/local/bin
    - chmod +x /usr/local/bin/vault
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=${VAULT_ROLE} jwt=$CI_JOB_JWT)"
    - export NPM_USER="$(vault kv get -field=username secrets/open-Digital-Factory/nexus/deployment)"
    - export NPM_PASS="$(vault kv get -field=password secrets/open-Digital-Factory/nexus/deployment)"
    - yarn config set npmScopes.aspect.npmPublishRegistry ${NPM_DEFAULT_REGISTRY}
    - yarn config set npmScopes.aspect.npmAuthIdent ${NPM_USER}:${NPM_PASS}
  script:
    - yarn workspace @aspect/react-ui npm publish
    - yarn workspace @aspect/design-system npm publish

