import type { ScenarioContent } from "../../core/scenario-api.service";
import type { DomainConfigResponse } from "../../core/domain-config-api.service";

export interface ScenarioExport {
  _llm_schema?: LlmSchema;
  title: string;
  description: string;
  content: ScenarioContent;
}

interface LlmSchema {
  _instructions: string;
  foundation: {
    roles: { id: string; label: string }[];
    systems: { id: string; label: string; category: string }[];
    warfare_domains: { id: string; label: string }[];
    blue_card_catalog: {
      id: string;
      title: string;
      targets_system: boolean;
    }[];
  };
  content_structure: Record<string, string>;
  turn_structure: Record<string, string>;
  example_turn: Record<string, unknown>;
  enums: Record<string, string[]>;
}

function buildLlmSchema(domain: DomainConfigResponse): LlmSchema {
  return {
    _instructions: [
      "This JSON defines a TFC (Training Flow Control) scenario.",
      "To generate a new scenario, keep the _llm_schema and modify title, description, and content.",
      "The 'content.turns' array is the primary authoring structure — one entry per game turn.",
      "Each turn contains: injects (per-role situation text), available_cards (blue cards the CO can pick), and consequences (stress/system/domain effects).",
      "Card IDs in available_cards must reference cards from foundation.blue_card_catalog.",
      "Role IDs in injects.target_roles must reference roles from foundation.roles.",
      "System IDs in system_effects must reference systems from foundation.systems.",
      "Domain IDs in domain_effects must reference domains from foundation.warfare_domains.",
      "Turn 0 should have has_decisions=false (pre-mission briefing, no blue cards).",
      "Turns 1+ should have has_decisions=true with available_cards defining the blue card options.",
      "Each card in available_cards has a per-turn score (points for picking it), stress_delta, and optional system_effects/domain_effects arrays.",
      "best_path and acceptable_path are facilitator notes documenting optimal/acceptable play.",
      "Do NOT populate the legacy fields: events, issues, decision_templates, phases, or decision_sequence — these are generated by the engine from turns.",
      "See content_structure for all top-level content fields and example_turn for a concrete turn example.",
    ].join(" "),
    foundation: {
      roles: domain.roles.map((r) => ({ id: r.id, label: r.label })),
      systems: domain.systems.map((s) => ({
        id: s.id,
        label: s.label,
        category: s.category,
      })),
      warfare_domains: domain.warfare_domains.map((w) => ({
        id: w.id,
        label: w.label,
      })),
      blue_card_catalog: domain.blue_card_catalog.map((c) => ({
        id: c.id,
        title: c.title,
        targets_system: c.targets_system,
      })),
    },
    content_structure: {
      game_mode: "string — see enums.game_mode",
      stress_effect_preset: "string — see enums.stress_effect_preset",
      game_mode_config:
        "object — mode-specific config (e.g., {base_decision_time_ms: 300000})",
      default_time_factor: "number — playback speed multiplier (default: 1.0)",
      briefing:
        "string — mission briefing text read to all players before Turn 0",
      objectives: "string[] — 3-5 mission objectives",
      rules: "string[] — exercise rules shown to players",
      roles:
        "array of {id, label, player_type} — must match foundation.roles IDs",
      initial_system_states:
        "array of {system_id, label, category, operational_state, power_state} — starting board state; IDs must match foundation.systems",
      initial_warfare_domains:
        "array of {domain_id, label, initial_threat_level} — starting domain state; IDs must match foundation.warfare_domains",
      turns: "TurnDefinition[] — the primary authored content (see turn_structure)",
      score_tier_thresholds:
        '{"lo": number, "mid": number} — fraction thresholds for Lo/Mid/Hi scoring tiers',
    },
    turn_structure: {
      turn_index: "number — auto-incremented, 0-based",
      title: "string — short turn title (e.g., 'Steady Approach')",
      facilitator_prompt:
        "string|null — what the facilitator reads aloud to players",
      has_decisions:
        "boolean — false for briefing turns (Turn 0), true for decision turns",
      duration_ms:
        "number|null — only for non-decision turns (e.g., 900000 = 15 min)",
      "injects[]":
        "array of {target_roles: string[], text: string} — per-role situation updates",
      "available_cards[]":
        "array of {card_id: string, score: number, stress_delta: number, system_effects?: SystemEffectDef[], domain_effects?: DomainEffectDef[]} — blue cards available this turn; effects trigger when the card is played",
      max_selections: "number — how many cards the CO can pick (default: 2)",
      base_stress_delta:
        "number — stress change applied at turn start regardless of card choice",
      "system_effects_on_start[]":
        "array of {system_id, operational_state: green|yellow|red, power_state: boolean} — board changes at turn start",
      "domain_effects_on_start[]":
        "array of {domain_id, threat_level: green|yellow|red} — domain threat changes at turn start",
      best_path:
        "{card_ids: string[], notes: string}|null — optimal card combination + why",
      acceptable_path:
        "{card_ids: string[], notes: string}|null — suboptimal but valid alternative",
      design_notes:
        "string — why this turn exists, what it teaches (facilitator-only)",
    },
    example_turn: {
      turn_index: 3,
      title: "Hostile Contact",
      facilitator_prompt:
        "Warship confirmed on radar. Raise urgency — let players decide response.",
      has_decisions: true,
      injects: [
        {
          target_roles: ["nav", "pwo"],
          text: "Warship contact bearing 052, range 12 nm. ESM confirms non-commercial emissions.",
        },
      ],
      available_cards: [
        { card_id: "SWB20", score: 10, stress_delta: 0 },
        {
          card_id: "SWB10",
          score: 8,
          stress_delta: 0,
          system_effects: [
            { system_id: "cic_network", power_state: false },
          ],
        },
        { card_id: "SWB01", score: 4, stress_delta: 1 },
      ],
      max_selections: 2,
      base_stress_delta: 1,
      domain_effects_on_start: [
        { domain_id: "asuw", threat_level: "yellow" },
      ],
      best_path: {
        card_ids: ["SWB20", "SWB10"],
        notes: "General Quarters + Isolate network to contain lateral movement.",
      },
      design_notes:
        "Escalation turn — first kinetic threat. Tests whether players prioritise defence posture over investigation.",
    },
    enums: {
      operational_state: ["green", "yellow", "red"],
      threat_level: ["green", "yellow", "red"],
      game_mode: ["classic", "simple_collaborative"],
      stress_effect_preset: ["off", "mild", "standard", "intense"],
      player_type: ["decision_maker", "advisor"],
      system_category: ["system", "weapon"],
    },
  };
}

export function exportScenarioToJson(
  title: string,
  description: string,
  content: ScenarioContent,
  domain?: DomainConfigResponse,
): Blob {
  const data: ScenarioExport = { title, description, content };
  if (domain) {
    data._llm_schema = buildLlmSchema(domain);
  }
  return new Blob([JSON.stringify(data, null, 2)], {
    type: "application/json",
  });
}

export function parseScenarioImport(jsonString: string): ScenarioExport | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(jsonString);
  } catch {
    return null;
  }
  if (typeof parsed !== "object" || parsed === null) return null;
  // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion -- narrowed by typeof check above
  const obj = parsed as Record<string, unknown>;
  if (typeof obj["title"] !== "string") return null;
  if (typeof obj["content"] !== "object" || obj["content"] === null)
    return null;
  return {
    title: obj["title"],
    description:
      typeof obj["description"] === "string" ? obj["description"] : "",
    // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion -- validated above
    content: obj["content"] as ScenarioContent,
  };
}
