apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: boilerplate
spec:
  values:
    auth:
      postgresPassword: dev-postgres-password
      password: dev-password
    primary:
      persistence:
        size: 5Gi
