apiVersion: apps/v1
kind: Deployment
metadata:
  name: storybook
  namespace: boilerplate
spec:
  template:
    spec:
      containers:
        - name: storybook
          image: registry-cyberlab-ngb.naval-group.dev/naval-group/boilerplate:dev-000000-storybook
